### PR TITLE
Composer loading

### PR DESCRIPTION
**Pull request by hexmode**
These help with loading.

Tested with https://github.com/technion/maia_mailguard/pull/80

### CODE REVIEW

**Comment by gauthierm** [comment]
@hexmode Is the `include-path` needed? I'd like to keep it out if at all possible.

**Comment by hexmode** [comment]
> @hexmode Is the `include-path` needed? I'd like to keep it out if at all possible.

You could leave it out, but i think i needed it.  i'm not sure why right now.

I'll be returning to this, later, though, so I won't have time to test right now.

**Comment by gauthierm** [comment]
pear packages expect the php `include_path` to include where pear packages are installed.

If you're not using pear, this is an anti-feature as the composer autoloader works best and most efficiently when the include path is empty.

**Comment by gauthierm** [comment]
I'd like to merge this without the include-path change.

**Comment by gauthierm** [comment]
Replaced with https://github.com/silverorange/MDB2/pull/21

Since original author is not responding, closing this PR.

**Pull request closed without merging**
